export default [
  {
    id: '1',
    title: 'Purukan Jeremy',
    description: 'Ichad klo so kerja , so sukses jang lupa tpe jasa',
    image: require('./src/assets/icon/purukanAbout.png'),
    background: require('./src/assets/icon/wukongBg.jpg'),
    emailtitle: 'Email Address',
    email: 'jeremypurukan@gmail.com',
    phone: 'Phone Number',
    number: '+62-812-3164-4355',
  },
  {
    id: '2',
    title: 'Lapian, Jonathan',
    description: 'Toast',
    image: require('./src/assets/icon/LapianFoto.png'),
    background: require('./src/assets/icon/grassBg.jpg'),
    emailtitle: 'Email Address',
    email: 's22310315@student.unklab.ac.id',
    phone: 'Phone Number',
    number: '+62-815-2317-003',
  },
  {
    id: '3',
    title: 'Gerungan, Glenvidi Yosua',
    description: 'Kakak jer pahlawanku',
    image: require('./src/assets/icon/cipengAbout.png'),
    background: require('./src/assets/icon/jomokBg.jpg'),
    emailtitle: 'Email Address',
    email: 'tosans977@gmail.com',
    phone: 'Phone Number',
    number: '+62-857-9657-1024',
  },
  {
    id: '4',
    title: 'Taufik, Jonathan Vito',
    description: 'Jeremy Carry Us',
    image: require('./src/assets/icon/taufikAbout.png'),
    background: require('./src/assets/icon/wukongBg.jpg'),
    emailtitle: 'Email Address',
    email: 's22210132@student.unklab.ac.id',
    phone: 'Phone Number',
    number: '+62-899-8332-906',
  },
  {
    id: '5',
    title: 'Gerald, Lahea',
    description: 'Minimal So skripsi dua dek',
    image: require('./src/assets/icon/ichadAbout.png'),
    background: require('./src/assets/icon/wukongBg.jpg'),
    emailtitle: 'Email Address',
    email: 'laheaganteng@gmail.com',
    phone: 'Phone Number',
    number: '+62-896-9562-7930',
  },
];
